#!/usr/bin/env bash
# Copyright 2011-2015 Concurrent, Inc.
set -e

function show_usage {
  echo "Type multitool -h for the full help or multitool --selfupdate if you want to install the latest version."
  echo ""
  echo "To set a default platform, set the MULTITOOL_PLATFORM env variable."
}

if [ $# = 0 ]; then
  show_usage
  exit 1
fi

OPTION=$1
if [ "$OPTION" = "--selfupdate" ] ; then
  curl http://@location@/multitool/@majorVersion@/install-multitool.sh | bash
  exit $?
fi


# find the dir this is in, regardless of symlinkage. Modified from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  BASE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="BASE_DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
BASE_DIR="$( cd -P "$( dirname "$SOURCE" )/../" && pwd )"
BIN_DIR="$BASE_DIR/bin"
JAVA_EXEC=`which java`

MAIN_CLASS="multitool.Main"

PLATFORM=""
CONFIG=""
CONFIG_FILE=""

CASCADING_CONFIG_FILE=$HOME/.cascading/default.properties
LOCAL_CASCADING_CONFIG_FILE=$PWD/.cascading/default.properties

if [[ -e $LOCAL_CASCADING_CONFIG_FILE ]]; then
  CONFIG_FILE=$LOCAL_CASCADING_CONFIG_FILE
elif [[ -e $CASCADING_CONFIG_FILE ]]; then
  CONFIG_FILE=$CASCADING_CONFIG_FILE
fi

if [[ -n $MULTITOOL_PLATFORM ]]; then
  PLATFORM=$MULTITOOL_PLATFORM
elif [[ -n $CASCADING_PLATFORM ]]; then
  PLATFORM=$CASCADING_PLATFORM
elif [[ -n $CONFIG_FILE ]]; then
  PLATFORM=`grep '^multitool.platform.name' $CONFIG_FILE | cut -d\= -f2`
  if [[ -z $PLATFORM ]]; then
    PLATFORM=`grep '^cascading.platform.name' $CONFIG_FILE | cut -d\= -f2`
  fi
fi

if [[ -z $PLATFORM ]]; then
    # backwards compatibility
    PLATFORM=hadoop
fi

OPTIONS=

ARGS=("$@")

while [ -n "$1" ]
 do
     case $1 in
         # support for multitools cli parer, which needs the '=' to work
         # correclty
         --platform=local|--platform=hadoop|--platform=hadoop2-mr1|--platform=hadoop2-tez)
             PLATFORM=`echo $1 | awk -F\= '{ print $2 }'`
             shift
             ;;
         --debug)
             OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 ${OPTIONS}"
             shift
             ;;
         *)  # no more options. Stop while loop
             shift
             ;;
     esac
 done

MULTITOOL_CLASSPATH=""

case $PLATFORM in
   local)
       EXEC="$JAVA_EXEC -jar $BASE_DIR/platform/$PLATFORM/*jar"
       ;;
   hadoop)
       source $BIN_DIR/hadoop-env
       EXEC="$JAVA_EXEC -cp $($HADOOP_EXEC classpath):$(echo $BASE_DIR/platform/$PLATFORM/*.jar) $MAIN_CLASS"
       ;;
   hadoop2-mr1)
       source $BIN_DIR/yarn-env
       EXEC="$JAVA_EXEC -cp $($YARN_EXEC classpath):$(echo $BASE_DIR/platform/$PLATFORM/*.jar) $MAIN_CLASS"
       ;;
   hadoop2-tez)
       source $BIN_DIR/yarn-env
       source $BIN_DIR/tez-env
       EXEC="$JAVA_EXEC -cp $($YARN_EXEC classpath):$(echo $BASE_DIR/platform/$PLATFORM/*.jar) $MAIN_CLASS"
       ;;
   *)
       echo "ERROR: Unknown platform: $PLATFORM"
       exit 1
       ;;
esac

MULTITOOL_BIN_DIR=$BIN_DIR
MULTITOOL_BASE_DIR=$BASE_DIR

export MULTITOOL_BIN_DIR
export MULTITOOL_BASE_DIR
export MULTITOOL_PLATFORM=$PLATFORM

${EXEC} "${ARGS[@]}"
